- README.md
> Add Codenvy.io and Eclipse Che

- code-of-conduct.md
Keeping those crazy peeps civilized with a Code of Conduct.
Everyone is doing it :)
> Add a Code Of Conduct

- LICENSE
- README.md
Per the Awesome List requirements, this should not use a code license but instead use a creative commons license.
> Change the License to CC0

- README.md
Add a table of contents to the readme.
> Add a TOC to readme

- README.md
Cloud9 has been integrated as an AWS service, now being called AWS Cloud9.
> Update data of C9

- README.md
Adding Codiva.io Online Java Compiler and IDE to the existing users list.
- Multiple Tabbed editor
- Continuous compilation in the backend
- Autocompletion
- Mobile friendly
- Supports interactive programs
> Include Codiva.io Online Java Compiler and IDE

- README.md
* Add Go Playground
* Add SQLFiddle
> Add new snippets

- README.md
Run snippets of Python, JavaScript, TypeScript, Java, Ruby, C, and C++ code and see detailed step-by-step visualizations of run-time state
> Added Python Tutor

- README.md
Hi I added the official web IDE for Solidity a programming language that compiles to the EVM.
> Added remix as a web ide

- README.md
Added Codeboard.io as discussed, fixes #25
Tried to stay with the format you use for all other tools.
> Add Codeboard.io 

- README.md
> Add Nativescript Playground to Full IDE

- README.md
> Add Wide (Golang IDE)

- README.md
* [Glitch](https://glitch.com/) - Run full Node.js projects with support for automating hosting, version control, CDN for assets, secure storage of secrets, real-time collaboration, full console access, GitHub import/export, server-side debugger, instant deployments, and more
> Add Glitch

- README.md
- contributing.md
This adds a legend to the top so it's clear what each of the icons mean.
There is a new icon for "Sign Up Required" <img title="Sign Up Required" width="16" src="https://cdn.jsdelivr.net/npm/simple-icons@1.2.7/icons/shopify.svg" />
> Add a legend and "Sign Up Required" icon

- README.md
3v4l runs the most diverse set of versions compared to others. Includes alpha/beta's for upcoming releases
> Add 3v4l.org

- .travis.yml
- README.md
Let's avoid these markdown linting problems in the future 👍
> Add linting via Travis CI

- README.md
The new browxy version support more languages and multiple files
> Add Browxy

- README.md
The site doesn't use the https protocol
> Changed url of cpp.sh to http

- README.md
Appitr IDE : [https://ide.appitr.com/](https://ide.appitr.com/)
Example Projects : [https://ide.appitr.com/projects](https://ide.appitr.com/projects)
Documentation : [https://docs.appitr.com/](https://docs.appitr.com/)
> Add Appitr

- README.md
> Add webpaw.net

- README.md
mycompiler.io is an online code editor which currently supports 12 programming which includes C, C++, Java, Python, Ruby, Nodejs, C# and more.
- It supports auto code-completion and syntax highlighting.
- Collaborative features like forking, snippet sharing and commenting.
- Users can make an account and save their programs. All the saved programs can be viewed in one place.
- Social login support with Google, Facebook and Github.
- Multi device support- Phones, Tablets and Desktops.
> Add mycompiler.io

- README.md
Added [Coding Rooms](https://codingrooms.com/) to snippets IDEs
> Add Coding Rooms to snippets IDEs

- README.md
Adaface PairPro is a remote tool with shared code editor with compiler for 24+ programming languages. It comes with language documentation, video conferencing and interviewer modes.
> Add Adaface PairPro

- README.md
Wanted to follow up on https://github.com/styfle/awesome-online-ide/pull/53 since a lot has changed since then 😄 
Lmk if I'm missing anything or it needs to be reworded.
> Move Repl.it to Full IDE and update description

- README.md
Add Scastie - Scala playground
> Add Scastie

- README.md
> Runkit does not require sign in

- README.md
Adding Atheos IDE, a very easy to install and use web-based IDE
> Add Atheos IDE

- README.md
Run snippets from over 19 languages including C, C++, Python, JS, Go, Java and more. Programming guides with integrated code editor for effective learning.
> Add FreeCodeCompiler.com IDE
